name: Run Tests

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up CMake
      uses: actions/setup-cmake@v2
      with:
        cmake-version: '3.27.9' 

    - name: Install Criterion
      run: |
        sudo apt-get update
        sudo apt-get install -y libcriterion-dev

    - name: Build and test
      run: |
        mkdir build
        cd build
        cmake ..
        make
        ./LinkedListTests --verbose
